package main

import(
 "errors"
 "fmt"
 "net/http"
 "net/http/httptest"
 "os"
 "os/exec"
 "path/filepath"
 "strconv"
 "strings"
 "syscall"
 "testing"
 "time"
)

func testServer(before,after int,reset int64)*httptest.Server{mux:=http.NewServeMux();mux.HandleFunc("/rate_limit",func(w http.ResponseWriter,r *http.Request){w.Header().Set("Date","Wed, 01 Jan 2031 00:00:00 GMT");w.Header().Set("Content-Type","application/json");fmt.Fprintf(w,`{"resources":{"core":{"limit":60,"remaining":%d,"reset":%d}}}`,before,reset)});mux.HandleFunc("/repos/fufufu1116/multiverse-research/issues/74/comments",func(w http.ResponseWriter,r *http.Request){w.Header().Set("Date","Wed, 01 Jan 2031 00:00:00 GMT");w.Header().Set("X-RateLimit-Limit","60");w.Header().Set("X-RateLimit-Remaining",fmt.Sprint(after));w.Header().Set("X-RateLimit-Reset",fmt.Sprint(reset));w.Header().Set("X-RateLimit-Resource","core");w.WriteHeader(200);fmt.Fprint(w,"[]")});return httptest.NewServer(mux)}
func TestRateCommitFloors(t *testing.T){s:=testServer(60,59,1924995600);defer s.Close();r:=probeAt(s.URL,s.Client());if !r.Ready{t.Fatalf("60/59 not ready: %+v",r)};s2:=testServer(59,58,1924995600);defer s2.Close();r=probeAt(s2.URL,s2.Client());if r.Ready||r.Reason!="RATE_RESERVE_BEFORE"{t.Fatalf("59/58 accepted: %+v",r)};s3:=testServer(60,58,1924995600);defer s3.Close();r=probeAt(s3.URL,s3.Client());if r.Ready||r.Reason!="RATE_DECREMENT_NOT_EXACT_ONE"{t.Fatalf("bad decrement accepted: %+v",r)}}
func productionAnchorAvailable()bool{st,e:=os.Stat(lockPath);return e==nil&&st.IsDir()}
func ensureProductionEvidenceDirs(t *testing.T){t.Helper();for _,d:=range []string{filepath.Dir(statusPath),filepath.Dir(controlPath)}{if e:=os.MkdirAll(d,0755);e!=nil{t.Fatal(e)}}}
func TestUniqueTempPreexistingCollisionFailsClosed(t *testing.T){d:=t.TempDir();p:=filepath.Join(d,"status");gen:="11111111111111111111111111111111";tmp:=p+".tmp."+gen;if e:=os.WriteFile(tmp,[]byte("attacker"),0600);e!=nil{t.Fatal(e)};if e:=atomicReplaceUnique(p,"new",gen,0444);e==nil{t.Fatal("collision accepted")}}
func writePairFiles(t *testing.T,d,gen string)(string,string,string,string){t.Helper();status:=filepath.Join(d,"status");control:=filepath.Join(d,"control");st,ct:=render("rate-test",gen,"probe",probeResult{Ready:true,Reason:"READY",Before:60,After:59,Reset:1924995600});if e:=os.WriteFile(status,[]byte(st),0444);e!=nil{t.Fatal(e)};if e:=os.WriteFile(control,[]byte(ct),0644);e!=nil{t.Fatal(e)};return status,control,st,ct}
func TestFinalTargetSymlinkRejectedByAuthorityConsumer(t *testing.T){d:=t.TempDir();gen:="22222222222222222222222222222222";status,control,st,ct:=writePairFiles(t,d,gen);real:=filepath.Join(d,"real");if e:=os.WriteFile(real,[]byte(st),0444);e!=nil{t.Fatal(e)};if e:=os.Remove(status);e!=nil{t.Fatal(e)};if e:=os.Symlink(real,status);e!=nil{t.Fatal(e)};if e:=verifyPairExactAt(status,control,gen,st,ct);e==nil{t.Fatal("symlink accepted")}}
func TestFinalTargetHardlinkRejectedByAuthorityConsumer(t *testing.T){d:=t.TempDir();gen:="33333333333333333333333333333333";status,control,st,ct:=writePairFiles(t,d,gen);real:=filepath.Join(d,"real");if e:=os.WriteFile(real,[]byte(st),0444);e!=nil{t.Fatal(e)};if e:=os.Remove(status);e!=nil{t.Fatal(e)};if e:=os.Link(real,status);e!=nil{t.Fatal(e)};if e:=verifyPairExactAt(status,control,gen,st,ct);e==nil{t.Fatal("hardlink accepted")}}
func TestGenerationOrContentMismatchDenied(t *testing.T){d:=t.TempDir();gen:="44444444444444444444444444444444";status,control,st,ct:=writePairFiles(t,d,gen);if e:=os.WriteFile(control,[]byte(strings.Replace(ct,"runtime=`OFF`","runtime=`ON`",1)),0644);e!=nil{t.Fatal(e)};if e:=verifyPairExactAt(status,control,gen,st,ct);e==nil{t.Fatal("same-generation content mutation accepted")}}
func TestSealedAuthoritySnapshotImmutable(t *testing.T){r:=probeResult{Ready:true,Reason:"READY",Before:60,After:59,Reset:1924995600};gen:="55555555555555555555555555555555";st,ct:=render("rate-test",gen,"commit",r);a,e:=sealAuthority("rate-test",gen,r,st,ct);if e!=nil{t.Fatal(e)};defer a.File.Close();if e=verifySealedAuthority(a);e!=nil{t.Fatal(e)};if _,e=a.File.WriteAt([]byte("X"),0);e==nil{t.Fatal("sealed memfd write succeeded")};if e=verifySealedAuthority(a);e!=nil{t.Fatalf("sealed snapshot changed: %v",e)}}
func TestProductionLockAnchorRejectsPathReplacementAndSecondDomain(t *testing.T){if !productionAnchorAvailable(){t.Skip("exact image only")};l,e:=openLock(lockPath);if e!=nil{t.Fatal(e)};defer releaseLock(l);if e=os.Remove(lockPath);e==nil{t.Fatal("unlink anchor succeeded")};moved:=lockPath+".attacker";if e=os.Rename(lockPath,moved);e==nil{t.Fatal("rename anchor succeeded")};second,e:=openLockWithOperation(lockPath,syscall.LOCK_EX|syscall.LOCK_NB);if e==nil{releaseLock(second);t.Fatal("second lock succeeded")};if !errors.Is(e,syscall.EWOULDBLOCK)&&!errors.Is(e,syscall.EAGAIN){t.Fatalf("unexpected lock error: %v",e)}}
func TestIndependentPublisherProcessHelper(t *testing.T){if os.Getenv("V7R12_PUBLISH_HELPER")!="1"{return};d:=os.Getenv("V7R12_PUBLISH_DIR");gen:=os.Getenv("V7R12_PUBLISH_GEN");l,e:=openLock(lockPath);if e!=nil{os.Exit(97)};defer releaseLock(l);st,ct:=render("rate-test",gen,"probe",probeResult{Ready:true,Reason:"READY",Before:60,After:59,Reset:1924995600});if e=atomicReplaceUnique(filepath.Join(d,"status"),st,gen,0444);e!=nil{os.Exit(98)};if e=atomicReplaceUnique(filepath.Join(d,"control"),ct,gen,0644);e!=nil{os.Exit(99)};if e=verifyPairExactAt(filepath.Join(d,"status"),filepath.Join(d,"control"),gen,st,ct);e!=nil{os.Exit(100)};os.Exit(0)}
func TestConcurrentIndependentProcessesKeepGenerationPair(t *testing.T){if !productionAnchorAvailable(){t.Skip("exact image only")};d:=t.TempDir();var cmds []*exec.Cmd;for i:=0;i<8;i++{gen:=fmt.Sprintf("%032x",i+1);c:=exec.Command(os.Args[0],"-test.run=TestIndependentPublisherProcessHelper");c.Env=append(os.Environ(),"V7R12_PUBLISH_HELPER=1","V7R12_PUBLISH_DIR="+d,"V7R12_PUBLISH_GEN="+gen);if e:=c.Start();e!=nil{t.Fatal(e)};cmds=append(cmds,c)};for _,c:=range cmds{if e:=c.Wait();e!=nil{t.Fatal(e)}};sb,e:=os.ReadFile(filepath.Join(d,"status"));if e!=nil{t.Fatal(e)};cb,e:=os.ReadFile(filepath.Join(d,"control"));if e!=nil{t.Fatal(e)};if extractGeneration(string(sb))!=extractGeneration(string(cb)){t.Fatal("mixed generations")}}
func TestFinalBoundaryHolderHelper(t *testing.T){if os.Getenv("V7R12_FINAL_HOLDER")!="1"{return};signalDir:=os.Getenv("V7R12_SIGNAL_DIR");if signalDir==""{os.Exit(96)};ensureProductionEvidenceDirs(t);_=os.Remove(statusPath);_=os.Remove(controlPath);r:=probeResult{Ready:true,Reason:"READY",Before:60,After:59,Reset:1924995600};lock,gen,st,ct,e:=publishPair("rate-v7r12-test","commit",r,true);if e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(97)};defer releaseLock(lock);a,e:=prepareAuthorityTransition("rate-v7r12-test",gen,r,st,ct);if e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(98)};defer a.File.Close();meta:=fmt.Sprintf("pid=%d\nfd=%d\nsha=%s\n",os.Getpid(),a.File.Fd(),a.SHA256);if e=os.WriteFile(filepath.Join(signalDir,"ready"),[]byte(meta),0600);e!=nil{os.Exit(99)};deadline:=time.Now().Add(10*time.Second);for time.Now().Before(deadline){if _,e=os.Stat(filepath.Join(signalDir,"attacked"));e==nil{break};time.Sleep(10*time.Millisecond)};if _,e:=os.Stat(filepath.Join(signalDir,"attacked"));e!=nil{os.Exit(100)};if e=verifySealedAuthority(a);e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(101)};if e=verifyPairExactAt(statusPath,controlPath,gen,st,ct);e==nil{fmt.Fprintln(os.Stderr,"mutable mirrors unexpectedly remained exact");os.Exit(102)};if e=os.WriteFile(filepath.Join(signalDir,"sealed-ok"),[]byte(a.SHA256),0600);e!=nil{os.Exit(103)};os.Exit(0)}
func parseMeta(t *testing.T,b []byte)map[string]string{t.Helper();m:=map[string]string{};for _,ln:=range strings.Split(string(b),"\n"){if i:=strings.IndexByte(ln,'=');i>0{m[ln[:i]]=ln[i+1:]}};return m}
func TestFinalVerifyToExecSameUIDEvidenceMutationCannotAlterSealedAuthority(t *testing.T){if !productionAnchorAvailable(){t.Skip("exact image only")};ensureProductionEvidenceDirs(t);signalDir:=t.TempDir();holder:=exec.Command(os.Args[0],"-test.run=TestFinalBoundaryHolderHelper");holder.Env=append(os.Environ(),"V7R12_FINAL_HOLDER=1","V7R12_SIGNAL_DIR="+signalDir);if e:=holder.Start();e!=nil{t.Fatal(e)};deadline:=time.Now().Add(5*time.Second);readyPath:=filepath.Join(signalDir,"ready");for{if _,e:=os.Stat(readyPath);e==nil{break};if time.Now().After(deadline){_=holder.Process.Kill();t.Fatal("holder not ready")};time.Sleep(10*time.Millisecond)};b,e:=os.ReadFile(readyPath);if e!=nil{t.Fatal(e)};m:=parseMeta(t,b);pid,e:=strconv.Atoi(m["pid"]);if e!=nil{t.Fatal(e)};fd,e:=strconv.Atoi(m["fd"]);if e!=nil{t.Fatal(e)};if f,e:=os.Open(fmt.Sprintf("/proc/%d/fd/%d",pid,fd));e==nil{f.Close();_=holder.Process.Kill();t.Fatal("same-UID proc-fd access to nondumpable sealed authority succeeded")};if f,e:=os.OpenFile(fmt.Sprintf("/proc/%d/mem",pid),os.O_RDWR,0);e==nil{f.Close();_=holder.Process.Kill();t.Fatal("same-UID proc-mem access to nondumpable holder succeeded")};if e=os.WriteFile(controlPath,[]byte("attacker-in-place-control\n"),0644);e!=nil{_=holder.Process.Kill();t.Fatalf("control in-place attack did not exercise: %v",e)};for _,p:=range []string{statusPath,controlPath}{moved:=p+".attacker-moved";_=os.Remove(moved);if e=os.Rename(p,moved);e!=nil{_=holder.Process.Kill();t.Fatalf("rename attack %s: %v",p,e)};if e=os.WriteFile(p,[]byte("attacker-replacement\n"),0644);e!=nil{_=holder.Process.Kill();t.Fatalf("recreate attack %s: %v",p,e)};if e=os.Remove(p);e!=nil{_=holder.Process.Kill();t.Fatalf("unlink attack %s: %v",p,e)};if e=os.WriteFile(p,[]byte("attacker-second-replacement\n"),0644);e!=nil{_=holder.Process.Kill();t.Fatalf("second replacement %s: %v",p,e)}};if e=os.WriteFile(filepath.Join(signalDir,"attacked"),[]byte("done"),0600);e!=nil{_=holder.Process.Kill();t.Fatal(e)};if e=holder.Wait();e!=nil{t.Fatalf("holder failed after direct same-UID mutation: %v",e)};sealed,e:=os.ReadFile(filepath.Join(signalDir,"sealed-ok"));if e!=nil{t.Fatal(e)};if strings.TrimSpace(string(sealed))!=m["sha"]{t.Fatal("sealed authority hash changed")}}
func TestRenderMarksPathEvidenceNonAuthoritative(t *testing.T){s,c:=render("rate-test","00112233445566778899aabbccddeeff","commit",probeResult{Ready:true,Reason:"READY",Before:60,After:59,Reset:1924995600});for _,x:=range []string{s,c}{for _,want:=range []string{"SEALED_MEMFD_SNAPSHOT","OBSERVABILITY_ONLY","DUMPABLE_ZERO_BEFORE_FINAL_AUTHORITY","runtime"}{if !strings.Contains(x,want){t.Fatalf("missing %s",want)}}}}
