package main

import(
 "bufio";"crypto/sha256";"crypto/tls";"encoding/hex";"encoding/json";"errors";"fmt";"io";"net";"net/http";"os";"os/exec";"path/filepath";"runtime";"strconv";"strings";"syscall";"time"
)
const(
 runtimePath="/opt/multiverse/v36/runtime.py";manifestPath="/opt/multiverse/v36/closure-manifest.json";pythonPath="/usr/bin/python3";gitPath="/usr/bin/git";ghPath="/usr/bin/gh";triggerPath="/usr/local/bin/multiverse-v36-trigger";bindingPath="/opt/multiverse/v36/step3-binding.json";socketPath="/run/multiverse-v36-anchor.sock";receiptRoot="/dev/shm/multiverse-r1-stage1-phase-c-v19-7-36-v5-receipts";mainWant="5c1403c1f5aabb80d29e8c868440aede8888ce61";treeWant="3d47741b4863411e5c36cb4c28925ac455ab6441";tmpfsMagic=0x01021994
)
type Obj struct{Path,Type,Target,SHA256 string;Uid,Gid,Mode int;Size int64}
type Manifest struct{Version string `json:"version"`;Objects []Obj `json:"objects"`;Policy map[string]any `json:"policy"`}
type Row struct{State string `json:"state"`;Evidence string `json:"evidence"`}
func die(s string){fmt.Fprintln(os.Stderr,"PHASE_C_V19_7_36_V5_PRODUCER_DENIED:"+s);os.Exit(92)}
func cleanEnv(c,n string)[]string{return []string{"CODESPACES="+c,"CODESPACE_NAME="+n,"LANG=C","LC_ALL=C","PATH=/usr/bin:/bin","HOME=/nonexistent","XDG_CONFIG_HOME=/opt/multiverse/v36/empty-config","GIT_CONFIG_NOSYSTEM=1","GIT_CONFIG_GLOBAL=/dev/null","GIT_CONFIG_SYSTEM=/dev/null","GIT_TERMINAL_PROMPT=0","GIT_ASKPASS=/bin/false","SSH_ASKPASS=/bin/false","GH_CONFIG_DIR=/opt/multiverse/v36/empty-config","GH_BROWSER=/bin/false","GH_PAGER=cat"}}
func uid(fi os.FileInfo)(uint32,error){s,ok:=fi.Sys().(*syscall.Stat_t);if !ok{return 0,errors.New("stat")};return s.Uid,nil}
func rootChain(p string)error{r,e:=filepath.EvalSymlinks(p);if e!=nil{return e};for q:=r;;q=filepath.Dir(q){fi,e:=os.Lstat(q);if e!=nil{return e};u,e:=uid(fi);if e!=nil||u!=0||fi.Mode().Perm()&0022!=0{return fmt.Errorf("class-c:%s",q)};if q=="/"{break}};return nil}
func hashFile(p string)(int64,string,error){f,e:=os.Open(p);if e!=nil{return 0,"",e};defer f.Close();h:=sha256.New();n,e:=io.Copy(h,f);return n,hex.EncodeToString(h.Sum(nil)),e}
func loadManifest()(*Manifest,*os.File,error){if e:=rootChain(manifestPath);e!=nil{return nil,nil,e};f,e:=os.Open(manifestPath);if e!=nil{return nil,nil,e};b,e:=io.ReadAll(io.LimitReader(f,128<<20));if e!=nil{f.Close();return nil,nil,e};if _,e=f.Seek(0,0);e!=nil{f.Close();return nil,nil,e};var m Manifest;if json.Unmarshal(b,&m)!=nil||m.Version!="V19.7.36-v5"{f.Close();return nil,nil,errors.New("manifest")};return &m,f,nil}
func verifyManifest(m *Manifest)error{for _,o:=range m.Objects{if e:=rootChain(o.Path);e!=nil{return e};fi,e:=os.Lstat(o.Path);if e!=nil{return e};u,e:=uid(fi);if e!=nil||int(u)!=o.Uid||o.Uid!=0||int(fi.Mode().Perm())!=o.Mode{return fmt.Errorf("meta:%s",o.Path)};switch o.Type{case"file":n,h,e:=hashFile(o.Path);if e!=nil||n!=o.Size||h!=o.SHA256{return fmt.Errorf("hash:%s",o.Path)};case"symlink":t,e:=os.Readlink(o.Path);if e!=nil||t!=o.Target{return fmt.Errorf("link:%s",o.Path)};case"dir":if !fi.IsDir(){return fmt.Errorf("dir:%s",o.Path)};default:return fmt.Errorf("type:%s",o.Path)}};return nil}
func statusGate()error{b,e:=os.ReadFile("/proc/self/status");if e!=nil{return e};s:=string(b);if !strings.Contains(s,"NoNewPrivs:\t1"){return errors.New("nonewprivs")};get:=func(k string)(uint64,error){for _,l:=range strings.Split(s,"\n"){if strings.HasPrefix(l,k+":"){z:=strings.TrimSpace(strings.TrimPrefix(l,k+":"));return strconv.ParseUint(z,16,64)}};return 0,errors.New(k)};eff,e:=get("CapEff");if e!=nil{return e};bnd,e:=get("CapBnd");if e!=nil{return e};allowed:=uint64((1<<0)|(1<<6)|(1<<7));if eff&^allowed!=0||bnd&^allowed!=0||eff&(1<<21)!=0||bnd&(1<<21)!=0{return errors.New("caps")};u,e:=os.ReadFile("/proc/self/uid_map");if e!=nil{return e};if strings.TrimSpace(string(u))!="0          0 4294967295"&&strings.TrimSpace(string(u))!="0 0 4294967295"{return errors.New("userns")};return nil}
func mountGate()error{b,e:=os.ReadFile("/proc/self/mountinfo");if e!=nil{return e};trusted:=[]string{"/usr","/bin","/lib","/etc/ssl","/opt/multiverse"};for _,l:=range strings.Split(string(b),"\n"){f:=strings.Fields(l);if len(f)<6{continue};mp:=strings.ReplaceAll(f[4],"\\040"," ");if mp=="/"{continue};for _,t:=range trusted{if mp==t||strings.HasPrefix(mp,t+"/"){return fmt.Errorf("mount-overlay:%s",mp)}}};return nil}
func zeroSwap()bool{b,e:=os.ReadFile("/proc/swaps");return e==nil&&len(strings.Split(strings.TrimSpace(string(b)),"\n"))<=1}
func shmGate()error{var s syscall.Statfs_t;if syscall.Statfs("/dev/shm",&s)!=nil||uint64(s.Type)!=tmpfsMagic{return errors.New("shm")};return nil}
func strongReceipt(b []byte)error{if e:=shmGate();e!=nil{return e};if _,e:=os.Lstat(receiptRoot);!os.IsNotExist(e){return errors.New("receipt-preexists")};if e:=os.Mkdir(receiptRoot,0700);e!=nil{return e};d,e:=os.Open(receiptRoot);if e!=nil{return e};defer d.Close();fd,e:=syscall.Openat(int(d.Fd()),"PRE_PYTHON.json",syscall.O_RDWR|syscall.O_CREAT|syscall.O_EXCL|syscall.O_NOFOLLOW|syscall.O_CLOEXEC,0400);if e!=nil{return e};f:=os.NewFile(uintptr(fd),"receipt");defer f.Close();for off:=0;off<len(b);{n,e:=f.Write(b[off:]);if e!=nil||n<=0{return io.ErrShortWrite};off+=n};if e=f.Sync();e!=nil{return e};if _,e=f.Seek(0,0);e!=nil{return e};g,e:=io.ReadAll(f);if e!=nil||string(g)!=string(b){return errors.New("receipt-readback")};fi,e:=f.Stat();if e!=nil{return e};u,e:=uid(fi);if e!=nil||u!=0||!fi.Mode().IsRegular()||fi.Mode().Perm()!=0400||fi.Size()!=int64(len(b)){return errors.New("receipt-meta")};return d.Sync()}
func openC(p string)(*os.File,error){if e:=rootChain(p);e!=nil{return nil,e};return os.Open(p)}
func guarded(exe string,args []string,env []string)error{f,e:=openC(exe);if e!=nil{return e};defer f.Close();cmd:=exec.Command("/proc/self/fd/3",args...);cmd.ExtraFiles=[]*os.File{f};cmd.Env=env;cmd.Stdout=io.Discard;cmd.Stderr=io.Discard;return cmd.Run()}
func freshMain()error{tr:=&http.Transport{Proxy:nil,TLSClientConfig:&tls.Config{MinVersion:tls.VersionTLS12}};cl:=&http.Client{Transport:tr,Timeout:10*time.Second,CheckRedirect:func(r *http.Request,v []*http.Request)error{return http.ErrUseLastResponse}};get:=func(u string,v any)error{r,e:=http.NewRequest("GET",u,nil);if e!=nil{return e};r.Header.Set("Accept","application/vnd.github+json");x,e:=cl.Do(r);if e!=nil{return e};defer x.Body.Close();if x.StatusCode!=200{return fmt.Errorf("http:%d",x.StatusCode)};return json.NewDecoder(io.LimitReader(x.Body,1<<20)).Decode(v)};var ref struct{Object struct{SHA string `json:"sha"`} `json:"object"`};if e:=get("https://api.github.com/repos/fufufu1116/multiverse-research/git/ref/heads/main",&ref);e!=nil{return e};if ref.Object.SHA!=mainWant{return errors.New("main-drift")};var c struct{Tree struct{SHA string `json:"sha"`} `json:"tree"`};if e:=get("https://api.github.com/repos/fufufu1116/multiverse-research/git/commits/"+ref.Object.SHA,&c);e!=nil{return e};if c.Tree.SHA!=treeWant{return errors.New("tree-drift")};return nil}
func rows()map[string]Row{m:=map[string]Row{};p:=func(i int,e string){m[strconv.Itoa(i)]=Row{"PASS",e}};p(1,"Codespaces identity captured before clearenv");p(2,"static root-image producer on linux/amd64");p(3,"zero swap mechanically checked");p(4,"/dev/shm tmpfs mechanically checked");p(5,"/proc/self/fd available");p(6,"outer trigger and producer image-baked Class-C objects");p(7,"full frozen filesystem closure manifest reverified plus caps/mount substitution gate");p(8,"os.Clearenv before every dynamic child; fixed child environment");p(9,"Python executable opened once and actual invocation via inherited fd");p(10,"PyNaCl probe delegated to same runtime process after frozen closure gate");p(11,"git/gh/browser executables, libraries, git-core, configs, CA and guarded fd launcher frozen/reverified");p(12,"Fresh GitHub main ref and commit-tree proof performed by static producer");p(13,"image-baked nonmutating Step3 binding object reverified by closure manifest");m["14"]=Row{"POST_OAUTH_ONLY","credential-dependent identity/scope/ruleset/fence/environment proof forbidden before OAuth"};p(15,"pre-Python dirfd O_EXCL O_NOFOLLOW tmpfs receipt fsync/readback");p(16,"root image producer has no SYS_ADMIN and session UID has no mount/content authority");return m}
func runChain(codespaces,name string)error{if e:=statusGate();e!=nil{return e};if e:=mountGate();e!=nil{return e};if !zeroSwap(){return errors.New("swap")};if e:=shmGate();e!=nil{return e};m,mf,e:=loadManifest();if e!=nil{return e};defer mf.Close();if e=verifyManifest(m);e!=nil{return e};env:=cleanEnv(codespaces,name);if e=guarded(gitPath,[]string{"--version"},env);e!=nil{return fmt.Errorf("git:%w",e)};if e=guarded(ghPath,[]string{"--version"},env);e!=nil{return fmt.Errorf("gh:%w",e)};if e=freshMain();e!=nil{return fmt.Errorf("fresh-main:%w",e)};py,e:=openC(pythonPath);if e!=nil{return e};defer py.Close();rt,e:=openC(runtimePath);if e!=nil{return e};defer rt.Close();receipt,_:=json.Marshal(map[string]any{"version":"V19.7.36-v5","pre_python":true,"main":mainWant,"tree":treeWant});if e=strongReceipt(receipt);e!=nil{return e};ar,aw,e:=os.Pipe();if e!=nil{return e};defer ar.Close();a:=map[string]any{"version":"V19.7.36-v5","source":"ROOT_IMAGE_ANCHOR_PRODUCER_V5","environment":map[string]bool{"clearenv_before_dynamic_child":true,"fixed_child_env":true},"matrix":rows()};ab,_:=json.Marshal(a);go func(){defer aw.Close();for off:=0;off<len(ab);{n,e:=aw.Write(ab[off:]);if e!=nil||n<=0{return};off+=n}}();code:="import os;fd=int(os.environ['MULTIVERSE_V36_V5_RUNTIME_FD']);o=[]\nwhile True:\n b=os.read(fd,65536)\n if not b:break\n o.append(b)\nexec(compile(b''.join(o),'<v19.7.36-v5-runtime>','exec'),{'__name__':'__main__'})";cmd:=exec.Command("/proc/self/fd/3","-I","-S","-B","-c",code);cmd.ExtraFiles=[]*os.File{py,rt,mf,ar};cmd.Env=append(env,"MULTIVERSE_V36_V5_RUNTIME_FD=4","MULTIVERSE_V36_V5_MANIFEST_FD=5","MULTIVERSE_V36_V5_ATTEST_FD=6");cmd.Stdout=os.Stdout;cmd.Stderr=os.Stderr;cmd.SysProcAttr=&syscall.SysProcAttr{Credential:&syscall.Credential{Uid:1000,Gid:1000,NoSetGroups:true}};e=cmd.Run();if x,ok:=e.(*exec.ExitError);ok{if w,ok:=x.Sys().(syscall.WaitStatus);ok&&w.ExitStatus()==92{return nil}};return e}
func main(){if runtime.GOOS!="linux"||runtime.GOARCH!="amd64"||os.Geteuid()!=0{die("PLATFORM")};c:=os.Getenv("CODESPACES");n:=os.Getenv("CODESPACE_NAME");os.Clearenv();os.Setenv("LANG","C");os.Setenv("LC_ALL","C");if c!="true"||n==""{die("CODESPACES")};_ = os.Remove(socketPath);ln,e:=net.Listen("unix",socketPath);if e!=nil{die("SOCKET")};defer ln.Close();if e=os.Chown(socketPath,1000,1000);e!=nil{die("SOCKET_CHOWN")};if e=os.Chmod(socketPath,0600);e!=nil{die("SOCKET_MODE")};fmt.Fprintln(os.Stderr,"PHASE_C_V19_7_36_V5_ROOT_ANCHOR_READY");for{c,e:=ln.Accept();if e!=nil{die("ACCEPT")};func(){defer c.Close();uc:=c.(*net.UnixConn);raw,_:=uc.SyscallConn();var peer *syscall.Ucred;raw.Control(func(fd uintptr){peer,_=syscall.GetsockoptUcred(int(fd),syscall.SOL_SOCKET,syscall.SO_PEERCRED)});if peer==nil||peer.Uid!=1000{fmt.Fprintln(c,"DENIED PEER");return};s,e:=bufio.NewReader(io.LimitReader(c,64)).ReadString('\n');if e!=nil||s!="START V19.7.36-v5\n"{fmt.Fprintln(c,"DENIED PROTOCOL");return};if e=runChain(codespaces,n);e!=nil{fmt.Fprintln(c,"DENIED",e);return};fmt.Fprintln(c,"REVIEW_FREEZE_RC92_CONFIRMED")}()}}
