DB_PATH = 'multiverse_shared_engine.db'
LEASE_SECONDS = 120
ALLOWED_TRANSITIONS = {
    'PENDING': {'IN_IMPLEMENT','BLOCKED_TECHNICAL','FAILED_CLOSED','OWNER_GATE'},
    'IN_IMPLEMENT': {'IN_LAB','BLOCKED_TECHNICAL','FAILED_CLOSED','OWNER_GATE'},
    'IN_LAB': {'IN_AUDIT','LAB_FIX_REQUIRED','BLOCKED_TECHNICAL','FAILED_CLOSED','OWNER_GATE'},
    'LAB_FIX_REQUIRED': {'IN_IMPLEMENT','BLOCKED_TECHNICAL','FAILED_CLOSED','OWNER_GATE'},
    'IN_AUDIT': {'DONE','AUDIT_FIX_REQUIRED','BLOCKED_TECHNICAL','FAILED_CLOSED','OWNER_GATE'},
    'AUDIT_FIX_REQUIRED': {'IN_IMPLEMENT','BLOCKED_TECHNICAL','FAILED_CLOSED','OWNER_GATE'},
    'BLOCKED_TECHNICAL': {'PENDING','FAILED_CLOSED','OWNER_GATE'},
    'FAILED_CLOSED': set(), 'OWNER_GATE': set(), 'DONE': set(), 'ROLLED_BACK': set(),
}
